name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Inject Supabase Config
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Checking Secrets..."
          if [ -z "$SUPABASE_URL" ]; then
            echo "Error: SUPABASE_URL is not set"
            exit 1
          fi
          if [ -z "$SUPABASE_ANON_KEY" ]; then
            echo "Error: SUPABASE_ANON_KEY is not set"
            exit 1
          fi
          echo "✓ Secrets are configured"
          
          echo "Injecting config into index.html..."
          # 替换 index.html 中的占位符为内联配置
          CONFIG_SCRIPT="<script>\n    // Supabase Config (injected by GitHub Actions)\n    window.SUPABASE_URL='$SUPABASE_URL';\n    window.SUPABASE_ANON_KEY='$SUPABASE_ANON_KEY';\n    window.isConfigured=true;\n    console.log('✓ Supabase 配置已注入');\n    </script>"
          sed -i "s|<!-- SUPABASE_CONFIG_PLACEHOLDER -->|$CONFIG_SCRIPT|" index.html
          
          echo "✓ Configuration injected"
          echo "Verifying injection..."
          grep -A2 "Supabase Config" index.html || echo "Warning: Config not found in HTML"
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages
